public let MACARCHY_WINDOW_ID = "MACARCHY_WINDOW_ID"
public let MACARCHY_WORKSPACE = "MACARCHY_WORKSPACE"
public let MACARCHY_FOCUSED_WORKSPACE = "MACARCHY_FOCUSED_WORKSPACE"
public let MACARCHY_PREV_WORKSPACE = "MACARCHY_PREV_WORKSPACE"
