name: New Issue
description: New Issue
body:
  - type: textarea
    id: body
    attributes:
      label: Body
      value: |
        Describe the issue.

        ### Additional info

        Include the output of:

        ```shell
        $ macarchy --version
        ```
    validations:
      required: true
